# Generated by Django 4.1.5 on 2023-01-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('temperature', models.CharField(max_length=200)),
                ('precipitation', models.CharField(max_length=200)),
                ('wind', models.CharField(max_length=200)),
                ('cloudiness', models.CharField(max_length=200)),
            ],
        ),
    ]
